### ISSUE TITLE
Latest Legacy Version doesn't work on 1.8

### ISSUE THREAD

**Issue by Doxify** [iso2013/PacketEntityAPI#4] opened 2019-04-06 16:14 UTC
* Steps to reproduce
Start 1.8.8 server with the latest version of the Legacy jar

* Expected behavior
Load on startup

* Actual outcome
https://paste.ubuntu.com/p/YPttMpx6wm/

* Minecraft version *(Only 1.13 is officially supported)*
`This server is running CraftBukkit version git-PaperSpigot-"4c7641d" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)`

**Comment by iso2013** [comment] 2019-04-06 17:28
This is caused by the map in PacketEntityAPI, which maps entity types to their object IDs.
https://github.com/iso2013/PacketEntityAPI/blob/master/Plugin_Legacy/src/main/java/net/blitzcube/peapi/PacketEntityAPI.java#L54

If anyone would like to PR a fix for this (perhaps using JSON to load the map, depending on the version - much like structure.json), I'll take a look; however, I won't be writing specialized code for software that is nearing 5 years old :)

(Whoever adds 1.8 support would have to also create a new structure.json file)

**Closed by iso2013** 2019-04-06 17:28 UTC

**Comment by MoeXIV** [comment] 2020-02-04 03:28
A large majority of servers use 1.8.8, so I do think it is a valuable addition. We will just make a custom build for the time being.

**Comment by supertassu** [comment] 2020-02-04 06:33
Actually, according to bStats, 1.14.4 and 1.15.2 are currently most common server versions. https://bstats.org/global/bukkit#minecraftVersion
